# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from jethexa_controller_interfaces/RunActionSet.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RunActionSet(genpy.Message):
  _md5sum = "0956453a105a32316a59c54fb351ae16"
  _type = "jethexa_controller_interfaces/RunActionSet"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Request
string action_path
int32 repeat
bool interrupt
bool default_path
"""
  __slots__ = ['action_path','repeat','interrupt','default_path']
  _slot_types = ['string','int32','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       action_path,repeat,interrupt,default_path

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RunActionSet, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.action_path is None:
        self.action_path = ''
      if self.repeat is None:
        self.repeat = 0
      if self.interrupt is None:
        self.interrupt = False
      if self.default_path is None:
        self.default_path = False
    else:
      self.action_path = ''
      self.repeat = 0
      self.interrupt = False
      self.default_path = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.action_path
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_i2B().pack(_x.repeat, _x.interrupt, _x.default_path))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_path = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_path = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.repeat, _x.interrupt, _x.default_path,) = _get_struct_i2B().unpack(str[start:end])
      self.interrupt = bool(self.interrupt)
      self.default_path = bool(self.default_path)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.action_path
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_i2B().pack(_x.repeat, _x.interrupt, _x.default_path))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_path = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_path = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.repeat, _x.interrupt, _x.default_path,) = _get_struct_i2B().unpack(str[start:end])
      self.interrupt = bool(self.interrupt)
      self.default_path = bool(self.default_path)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i2B = None
def _get_struct_i2B():
    global _struct_i2B
    if _struct_i2B is None:
        _struct_i2B = struct.Struct("<i2B")
    return _struct_i2B
