# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from jethexa_controller_interfaces/SetHead.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import jethexa_controller_interfaces.msg

class SetHead(genpy.Message):
  _md5sum = "269ab51efb365ba39dc916c41e7ee5e2"
  _type = "jethexa_controller_interfaces/SetHead"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Euler rpy
float64 duration


================================================================================
MSG: jethexa_controller_interfaces/Euler
float64 roll
float64 pitch
float64 yaw"""
  __slots__ = ['rpy','duration']
  _slot_types = ['jethexa_controller_interfaces/Euler','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       rpy,duration

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SetHead, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.rpy is None:
        self.rpy = jethexa_controller_interfaces.msg.Euler()
      if self.duration is None:
        self.duration = 0.
    else:
      self.rpy = jethexa_controller_interfaces.msg.Euler()
      self.duration = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.rpy.roll, _x.rpy.pitch, _x.rpy.yaw, _x.duration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.rpy is None:
        self.rpy = jethexa_controller_interfaces.msg.Euler()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.rpy.roll, _x.rpy.pitch, _x.rpy.yaw, _x.duration,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.rpy.roll, _x.rpy.pitch, _x.rpy.yaw, _x.duration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.rpy is None:
        self.rpy = jethexa_controller_interfaces.msg.Euler()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.rpy.roll, _x.rpy.pitch, _x.rpy.yaw, _x.duration,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
