# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hexapod_msg/bodyTwist.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class bodyTwist(genpy.Message):
  _md5sum = "aebf5077596911a1b7b2a28523ac0efb"
  _type = "hexapod_msg/bodyTwist"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 angular_x
float64 angular_y
float64 angular_z
float64 linear_x
float64 linear_y
float64 linear_z
"""
  __slots__ = ['angular_x','angular_y','angular_z','linear_x','linear_y','linear_z']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       angular_x,angular_y,angular_z,linear_x,linear_y,linear_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(bodyTwist, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.angular_x is None:
        self.angular_x = 0.
      if self.angular_y is None:
        self.angular_y = 0.
      if self.angular_z is None:
        self.angular_z = 0.
      if self.linear_x is None:
        self.linear_x = 0.
      if self.linear_y is None:
        self.linear_y = 0.
      if self.linear_z is None:
        self.linear_z = 0.
    else:
      self.angular_x = 0.
      self.angular_y = 0.
      self.angular_z = 0.
      self.linear_x = 0.
      self.linear_y = 0.
      self.linear_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.angular_x, _x.angular_y, _x.angular_z, _x.linear_x, _x.linear_y, _x.linear_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.angular_x, _x.angular_y, _x.angular_z, _x.linear_x, _x.linear_y, _x.linear_z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.angular_x, _x.angular_y, _x.angular_z, _x.linear_x, _x.linear_y, _x.linear_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.angular_x, _x.angular_y, _x.angular_z, _x.linear_x, _x.linear_y, _x.linear_z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
