// Generated by gencpp from file hexapod_msg/bodyTwist.msg
// DO NOT EDIT!


#ifndef HEXAPOD_MSG_MESSAGE_BODYTWIST_H
#define HEXAPOD_MSG_MESSAGE_BODYTWIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hexapod_msg
{
template <class ContainerAllocator>
struct bodyTwist_
{
  typedef bodyTwist_<ContainerAllocator> Type;

  bodyTwist_()
    : angular_x(0.0)
    , angular_y(0.0)
    , angular_z(0.0)
    , linear_x(0.0)
    , linear_y(0.0)
    , linear_z(0.0)  {
    }
  bodyTwist_(const ContainerAllocator& _alloc)
    : angular_x(0.0)
    , angular_y(0.0)
    , angular_z(0.0)
    , linear_x(0.0)
    , linear_y(0.0)
    , linear_z(0.0)  {
  (void)_alloc;
    }



   typedef double _angular_x_type;
  _angular_x_type angular_x;

   typedef double _angular_y_type;
  _angular_y_type angular_y;

   typedef double _angular_z_type;
  _angular_z_type angular_z;

   typedef double _linear_x_type;
  _linear_x_type linear_x;

   typedef double _linear_y_type;
  _linear_y_type linear_y;

   typedef double _linear_z_type;
  _linear_z_type linear_z;





  typedef boost::shared_ptr< ::hexapod_msg::bodyTwist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hexapod_msg::bodyTwist_<ContainerAllocator> const> ConstPtr;

}; // struct bodyTwist_

typedef ::hexapod_msg::bodyTwist_<std::allocator<void> > bodyTwist;

typedef boost::shared_ptr< ::hexapod_msg::bodyTwist > bodyTwistPtr;
typedef boost::shared_ptr< ::hexapod_msg::bodyTwist const> bodyTwistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hexapod_msg::bodyTwist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hexapod_msg::bodyTwist_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hexapod_msg::bodyTwist_<ContainerAllocator1> & lhs, const ::hexapod_msg::bodyTwist_<ContainerAllocator2> & rhs)
{
  return lhs.angular_x == rhs.angular_x &&
    lhs.angular_y == rhs.angular_y &&
    lhs.angular_z == rhs.angular_z &&
    lhs.linear_x == rhs.linear_x &&
    lhs.linear_y == rhs.linear_y &&
    lhs.linear_z == rhs.linear_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hexapod_msg::bodyTwist_<ContainerAllocator1> & lhs, const ::hexapod_msg::bodyTwist_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hexapod_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hexapod_msg::bodyTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hexapod_msg::bodyTwist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hexapod_msg::bodyTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hexapod_msg::bodyTwist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hexapod_msg::bodyTwist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hexapod_msg::bodyTwist_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hexapod_msg::bodyTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aebf5077596911a1b7b2a28523ac0efb";
  }

  static const char* value(const ::hexapod_msg::bodyTwist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaebf5077596911a1ULL;
  static const uint64_t static_value2 = 0xb7b2a28523ac0efbULL;
};

template<class ContainerAllocator>
struct DataType< ::hexapod_msg::bodyTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hexapod_msg/bodyTwist";
  }

  static const char* value(const ::hexapod_msg::bodyTwist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hexapod_msg::bodyTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angular_x\n"
"float64 angular_y\n"
"float64 angular_z\n"
"float64 linear_x\n"
"float64 linear_y\n"
"float64 linear_z\n"
;
  }

  static const char* value(const ::hexapod_msg::bodyTwist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hexapod_msg::bodyTwist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angular_x);
      stream.next(m.angular_y);
      stream.next(m.angular_z);
      stream.next(m.linear_x);
      stream.next(m.linear_y);
      stream.next(m.linear_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bodyTwist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hexapod_msg::bodyTwist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hexapod_msg::bodyTwist_<ContainerAllocator>& v)
  {
    s << indent << "angular_x: ";
    Printer<double>::stream(s, indent + "  ", v.angular_x);
    s << indent << "angular_y: ";
    Printer<double>::stream(s, indent + "  ", v.angular_y);
    s << indent << "angular_z: ";
    Printer<double>::stream(s, indent + "  ", v.angular_z);
    s << indent << "linear_x: ";
    Printer<double>::stream(s, indent + "  ", v.linear_x);
    s << indent << "linear_y: ";
    Printer<double>::stream(s, indent + "  ", v.linear_y);
    s << indent << "linear_z: ";
    Printer<double>::stream(s, indent + "  ", v.linear_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEXAPOD_MSG_MESSAGE_BODYTWIST_H
