// Generated by gencpp from file jethexa_controller_interfaces/LegPosition.msg
// DO NOT EDIT!


#ifndef JETHEXA_CONTROLLER_INTERFACES_MESSAGE_LEGPOSITION_H
#define JETHEXA_CONTROLLER_INTERFACES_MESSAGE_LEGPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace jethexa_controller_interfaces
{
template <class ContainerAllocator>
struct LegPosition_
{
  typedef LegPosition_<ContainerAllocator> Type;

  LegPosition_()
    : leg_id(0)
    , duration(0.0)
    , position()  {
    }
  LegPosition_(const ContainerAllocator& _alloc)
    : leg_id(0)
    , duration(0.0)
    , position(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _leg_id_type;
  _leg_id_type leg_id;

   typedef float _duration_type;
  _duration_type duration;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator> const> ConstPtr;

}; // struct LegPosition_

typedef ::jethexa_controller_interfaces::LegPosition_<std::allocator<void> > LegPosition;

typedef boost::shared_ptr< ::jethexa_controller_interfaces::LegPosition > LegPositionPtr;
typedef boost::shared_ptr< ::jethexa_controller_interfaces::LegPosition const> LegPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator1> & lhs, const ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator2> & rhs)
{
  return lhs.leg_id == rhs.leg_id &&
    lhs.duration == rhs.duration &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator1> & lhs, const ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jethexa_controller_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6950a434049c35d066c094e6cf6b87eb";
  }

  static const char* value(const ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6950a434049c35d0ULL;
  static const uint64_t static_value2 = 0x66c094e6cf6b87ebULL;
};

template<class ContainerAllocator>
struct DataType< ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jethexa_controller_interfaces/LegPosition";
  }

  static const char* value(const ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 leg_id\n"
"float32 duration\n"
"geometry_msgs/Point position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leg_id);
      stream.next(m.duration);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jethexa_controller_interfaces::LegPosition_<ContainerAllocator>& v)
  {
    s << indent << "leg_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.leg_id);
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETHEXA_CONTROLLER_INTERFACES_MESSAGE_LEGPOSITION_H
