// Generated by gencpp from file jethexa_controller_interfaces/LegsJoints.msg
// DO NOT EDIT!


#ifndef JETHEXA_CONTROLLER_INTERFACES_MESSAGE_LEGSJOINTS_H
#define JETHEXA_CONTROLLER_INTERFACES_MESSAGE_LEGSJOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <jethexa_controller_interfaces/LegJoints.h>

namespace jethexa_controller_interfaces
{
template <class ContainerAllocator>
struct LegsJoints_
{
  typedef LegsJoints_<ContainerAllocator> Type;

  LegsJoints_()
    : leg()  {
    }
  LegsJoints_(const ContainerAllocator& _alloc)
    : leg()  {
  (void)_alloc;
      leg.assign( ::jethexa_controller_interfaces::LegJoints_<ContainerAllocator> (_alloc));
  }



   typedef boost::array< ::jethexa_controller_interfaces::LegJoints_<ContainerAllocator> , 6>  _leg_type;
  _leg_type leg;





  typedef boost::shared_ptr< ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator> const> ConstPtr;

}; // struct LegsJoints_

typedef ::jethexa_controller_interfaces::LegsJoints_<std::allocator<void> > LegsJoints;

typedef boost::shared_ptr< ::jethexa_controller_interfaces::LegsJoints > LegsJointsPtr;
typedef boost::shared_ptr< ::jethexa_controller_interfaces::LegsJoints const> LegsJointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator1> & lhs, const ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator2> & rhs)
{
  return lhs.leg == rhs.leg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator1> & lhs, const ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jethexa_controller_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77281f1f9c4cd29d21908d690db99185";
  }

  static const char* value(const ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77281f1f9c4cd29dULL;
  static const uint64_t static_value2 = 0x21908d690db99185ULL;
};

template<class ContainerAllocator>
struct DataType< ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jethexa_controller_interfaces/LegsJoints";
  }

  static const char* value(const ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "LegJoints[6] leg\n"
"================================================================================\n"
"MSG: jethexa_controller_interfaces/LegJoints\n"
"float64 coxa\n"
"float64 femur\n"
"float64 tibia\n"
"float64 tarsus\n"
;
  }

  static const char* value(const ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegsJoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jethexa_controller_interfaces::LegsJoints_<ContainerAllocator>& v)
  {
    s << indent << "leg[]" << std::endl;
    for (size_t i = 0; i < v.leg.size(); ++i)
    {
      s << indent << "  leg[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::jethexa_controller_interfaces::LegJoints_<ContainerAllocator> >::stream(s, indent + "    ", v.leg[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETHEXA_CONTROLLER_INTERFACES_MESSAGE_LEGSJOINTS_H
