// Generated by gencpp from file jethexa_controller_interfaces/PoseTransform.msg
// DO NOT EDIT!


#ifndef JETHEXA_CONTROLLER_INTERFACES_MESSAGE_POSETRANSFORM_H
#define JETHEXA_CONTROLLER_INTERFACES_MESSAGE_POSETRANSFORM_H

#include <ros/service_traits.h>


#include <jethexa_controller_interfaces/PoseTransformRequest.h>
#include <jethexa_controller_interfaces/PoseTransformResponse.h>


namespace jethexa_controller_interfaces
{

struct PoseTransform
{

typedef PoseTransformRequest Request;
typedef PoseTransformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PoseTransform
} // namespace jethexa_controller_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jethexa_controller_interfaces::PoseTransform > {
  static const char* value()
  {
    return "4cd99d259c76651e37d160a72014e6f9";
  }

  static const char* value(const ::jethexa_controller_interfaces::PoseTransform&) { return value(); }
};

template<>
struct DataType< ::jethexa_controller_interfaces::PoseTransform > {
  static const char* value()
  {
    return "jethexa_controller_interfaces/PoseTransform";
  }

  static const char* value(const ::jethexa_controller_interfaces::PoseTransform&) { return value(); }
};


// service_traits::MD5Sum< ::jethexa_controller_interfaces::PoseTransformRequest> should match
// service_traits::MD5Sum< ::jethexa_controller_interfaces::PoseTransform >
template<>
struct MD5Sum< ::jethexa_controller_interfaces::PoseTransformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jethexa_controller_interfaces::PoseTransform >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::PoseTransformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jethexa_controller_interfaces::PoseTransformRequest> should match
// service_traits::DataType< ::jethexa_controller_interfaces::PoseTransform >
template<>
struct DataType< ::jethexa_controller_interfaces::PoseTransformRequest>
{
  static const char* value()
  {
    return DataType< ::jethexa_controller_interfaces::PoseTransform >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::PoseTransformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jethexa_controller_interfaces::PoseTransformResponse> should match
// service_traits::MD5Sum< ::jethexa_controller_interfaces::PoseTransform >
template<>
struct MD5Sum< ::jethexa_controller_interfaces::PoseTransformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jethexa_controller_interfaces::PoseTransform >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::PoseTransformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jethexa_controller_interfaces::PoseTransformResponse> should match
// service_traits::DataType< ::jethexa_controller_interfaces::PoseTransform >
template<>
struct DataType< ::jethexa_controller_interfaces::PoseTransformResponse>
{
  static const char* value()
  {
    return DataType< ::jethexa_controller_interfaces::PoseTransform >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::PoseTransformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETHEXA_CONTROLLER_INTERFACES_MESSAGE_POSETRANSFORM_H
