// Generated by gencpp from file jethexa_controller_interfaces/PoseTransformResponse.msg
// DO NOT EDIT!


#ifndef JETHEXA_CONTROLLER_INTERFACES_MESSAGE_POSETRANSFORMRESPONSE_H
#define JETHEXA_CONTROLLER_INTERFACES_MESSAGE_POSETRANSFORMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jethexa_controller_interfaces
{
template <class ContainerAllocator>
struct PoseTransformResponse_
{
  typedef PoseTransformResponse_<ContainerAllocator> Type;

  PoseTransformResponse_()
    : result(0)
    , message()  {
    }
  PoseTransformResponse_(const ContainerAllocator& _alloc)
    : result(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PoseTransformResponse_

typedef ::jethexa_controller_interfaces::PoseTransformResponse_<std::allocator<void> > PoseTransformResponse;

typedef boost::shared_ptr< ::jethexa_controller_interfaces::PoseTransformResponse > PoseTransformResponsePtr;
typedef boost::shared_ptr< ::jethexa_controller_interfaces::PoseTransformResponse const> PoseTransformResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator1> & lhs, const ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator1> & lhs, const ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jethexa_controller_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81f429c124a47a1dc0c7e925328a2d0c";
  }

  static const char* value(const ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81f429c124a47a1dULL;
  static const uint64_t static_value2 = 0xc0c7e925328a2d0cULL;
};

template<class ContainerAllocator>
struct DataType< ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jethexa_controller_interfaces/PoseTransformResponse";
  }

  static const char* value(const ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseTransformResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jethexa_controller_interfaces::PoseTransformResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETHEXA_CONTROLLER_INTERFACES_MESSAGE_POSETRANSFORMRESPONSE_H
