// Generated by gencpp from file jethexa_controller_interfaces/SetFloat64.msg
// DO NOT EDIT!


#ifndef JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETFLOAT64_H
#define JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETFLOAT64_H

#include <ros/service_traits.h>


#include <jethexa_controller_interfaces/SetFloat64Request.h>
#include <jethexa_controller_interfaces/SetFloat64Response.h>


namespace jethexa_controller_interfaces
{

struct SetFloat64
{

typedef SetFloat64Request Request;
typedef SetFloat64Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat64
} // namespace jethexa_controller_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jethexa_controller_interfaces::SetFloat64 > {
  static const char* value()
  {
    return "3f47c51e9da05852f0d7f484f9279955";
  }

  static const char* value(const ::jethexa_controller_interfaces::SetFloat64&) { return value(); }
};

template<>
struct DataType< ::jethexa_controller_interfaces::SetFloat64 > {
  static const char* value()
  {
    return "jethexa_controller_interfaces/SetFloat64";
  }

  static const char* value(const ::jethexa_controller_interfaces::SetFloat64&) { return value(); }
};


// service_traits::MD5Sum< ::jethexa_controller_interfaces::SetFloat64Request> should match
// service_traits::MD5Sum< ::jethexa_controller_interfaces::SetFloat64 >
template<>
struct MD5Sum< ::jethexa_controller_interfaces::SetFloat64Request>
{
  static const char* value()
  {
    return MD5Sum< ::jethexa_controller_interfaces::SetFloat64 >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::SetFloat64Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::jethexa_controller_interfaces::SetFloat64Request> should match
// service_traits::DataType< ::jethexa_controller_interfaces::SetFloat64 >
template<>
struct DataType< ::jethexa_controller_interfaces::SetFloat64Request>
{
  static const char* value()
  {
    return DataType< ::jethexa_controller_interfaces::SetFloat64 >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::SetFloat64Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jethexa_controller_interfaces::SetFloat64Response> should match
// service_traits::MD5Sum< ::jethexa_controller_interfaces::SetFloat64 >
template<>
struct MD5Sum< ::jethexa_controller_interfaces::SetFloat64Response>
{
  static const char* value()
  {
    return MD5Sum< ::jethexa_controller_interfaces::SetFloat64 >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::SetFloat64Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::jethexa_controller_interfaces::SetFloat64Response> should match
// service_traits::DataType< ::jethexa_controller_interfaces::SetFloat64 >
template<>
struct DataType< ::jethexa_controller_interfaces::SetFloat64Response>
{
  static const char* value()
  {
    return DataType< ::jethexa_controller_interfaces::SetFloat64 >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::SetFloat64Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETFLOAT64_H
