// Generated by gencpp from file jethexa_controller_interfaces/SetFloat64List.msg
// DO NOT EDIT!


#ifndef JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETFLOAT64LIST_H
#define JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETFLOAT64LIST_H

#include <ros/service_traits.h>


#include <jethexa_controller_interfaces/SetFloat64ListRequest.h>
#include <jethexa_controller_interfaces/SetFloat64ListResponse.h>


namespace jethexa_controller_interfaces
{

struct SetFloat64List
{

typedef SetFloat64ListRequest Request;
typedef SetFloat64ListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat64List
} // namespace jethexa_controller_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jethexa_controller_interfaces::SetFloat64List > {
  static const char* value()
  {
    return "5739026f6f0517440e663ba60441de94";
  }

  static const char* value(const ::jethexa_controller_interfaces::SetFloat64List&) { return value(); }
};

template<>
struct DataType< ::jethexa_controller_interfaces::SetFloat64List > {
  static const char* value()
  {
    return "jethexa_controller_interfaces/SetFloat64List";
  }

  static const char* value(const ::jethexa_controller_interfaces::SetFloat64List&) { return value(); }
};


// service_traits::MD5Sum< ::jethexa_controller_interfaces::SetFloat64ListRequest> should match
// service_traits::MD5Sum< ::jethexa_controller_interfaces::SetFloat64List >
template<>
struct MD5Sum< ::jethexa_controller_interfaces::SetFloat64ListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jethexa_controller_interfaces::SetFloat64List >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::SetFloat64ListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jethexa_controller_interfaces::SetFloat64ListRequest> should match
// service_traits::DataType< ::jethexa_controller_interfaces::SetFloat64List >
template<>
struct DataType< ::jethexa_controller_interfaces::SetFloat64ListRequest>
{
  static const char* value()
  {
    return DataType< ::jethexa_controller_interfaces::SetFloat64List >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::SetFloat64ListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jethexa_controller_interfaces::SetFloat64ListResponse> should match
// service_traits::MD5Sum< ::jethexa_controller_interfaces::SetFloat64List >
template<>
struct MD5Sum< ::jethexa_controller_interfaces::SetFloat64ListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jethexa_controller_interfaces::SetFloat64List >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::SetFloat64ListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jethexa_controller_interfaces::SetFloat64ListResponse> should match
// service_traits::DataType< ::jethexa_controller_interfaces::SetFloat64List >
template<>
struct DataType< ::jethexa_controller_interfaces::SetFloat64ListResponse>
{
  static const char* value()
  {
    return DataType< ::jethexa_controller_interfaces::SetFloat64List >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::SetFloat64ListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETFLOAT64LIST_H
