// Generated by gencpp from file jethexa_controller_interfaces/SetInt64Request.msg
// DO NOT EDIT!


#ifndef JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETINT64REQUEST_H
#define JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETINT64REQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jethexa_controller_interfaces
{
template <class ContainerAllocator>
struct SetInt64Request_
{
  typedef SetInt64Request_<ContainerAllocator> Type;

  SetInt64Request_()
    : data(0)  {
    }
  SetInt64Request_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef int64_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator> const> ConstPtr;

}; // struct SetInt64Request_

typedef ::jethexa_controller_interfaces::SetInt64Request_<std::allocator<void> > SetInt64Request;

typedef boost::shared_ptr< ::jethexa_controller_interfaces::SetInt64Request > SetInt64RequestPtr;
typedef boost::shared_ptr< ::jethexa_controller_interfaces::SetInt64Request const> SetInt64RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator1> & lhs, const ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator1> & lhs, const ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jethexa_controller_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34add168574510e6e17f5d23ecc077ef";
  }

  static const char* value(const ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34add168574510e6ULL;
  static const uint64_t static_value2 = 0xe17f5d23ecc077efULL;
};

template<class ContainerAllocator>
struct DataType< ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jethexa_controller_interfaces/SetInt64Request";
  }

  static const char* value(const ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 data\n"
;
  }

  static const char* value(const ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetInt64Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jethexa_controller_interfaces::SetInt64Request_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<int64_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETINT64REQUEST_H
