// Generated by gencpp from file jethexa_controller_interfaces/SetPose2Request.msg
// DO NOT EDIT!


#ifndef JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETPOSE2REQUEST_H
#define JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETPOSE2REQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point32.h>

namespace jethexa_controller_interfaces
{
template <class ContainerAllocator>
struct SetPose2Request_
{
  typedef SetPose2Request_<ContainerAllocator> Type;

  SetPose2Request_()
    : pose()
    , duration(0.0)
    , interrupt(false)  {
    }
  SetPose2Request_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , duration(0.0)
    , interrupt(false)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point32_<ContainerAllocator> >> _pose_type;
  _pose_type pose;

   typedef float _duration_type;
  _duration_type duration;

   typedef uint8_t _interrupt_type;
  _interrupt_type interrupt;





  typedef boost::shared_ptr< ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator> const> ConstPtr;

}; // struct SetPose2Request_

typedef ::jethexa_controller_interfaces::SetPose2Request_<std::allocator<void> > SetPose2Request;

typedef boost::shared_ptr< ::jethexa_controller_interfaces::SetPose2Request > SetPose2RequestPtr;
typedef boost::shared_ptr< ::jethexa_controller_interfaces::SetPose2Request const> SetPose2RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator1> & lhs, const ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.duration == rhs.duration &&
    lhs.interrupt == rhs.interrupt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator1> & lhs, const ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jethexa_controller_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77347ab8ab6b6ff8643459d887040520";
  }

  static const char* value(const ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77347ab8ab6b6ff8ULL;
  static const uint64_t static_value2 = 0x643459d887040520ULL;
};

template<class ContainerAllocator>
struct DataType< ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jethexa_controller_interfaces/SetPose2Request";
  }

  static const char* value(const ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point32[] pose\n"
"float32 duration\n"
"bool interrupt\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.duration);
      stream.next(m.interrupt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPose2Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jethexa_controller_interfaces::SetPose2Request_<ContainerAllocator>& v)
  {
    s << indent << "pose[]" << std::endl;
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      s << indent << "  pose[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.pose[i]);
    }
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
    s << indent << "interrupt: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.interrupt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETPOSE2REQUEST_H
