// Generated by gencpp from file jethexa_controller_interfaces/SetPose1.msg
// DO NOT EDIT!


#ifndef JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETPOSE1_H
#define JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETPOSE1_H

#include <ros/service_traits.h>


#include <jethexa_controller_interfaces/SetPose1Request.h>
#include <jethexa_controller_interfaces/SetPose1Response.h>


namespace jethexa_controller_interfaces
{

struct SetPose1
{

typedef SetPose1Request Request;
typedef SetPose1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose1
} // namespace jethexa_controller_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jethexa_controller_interfaces::SetPose1 > {
  static const char* value()
  {
    return "13028fae944c7d292e6d7a20d1f599d6";
  }

  static const char* value(const ::jethexa_controller_interfaces::SetPose1&) { return value(); }
};

template<>
struct DataType< ::jethexa_controller_interfaces::SetPose1 > {
  static const char* value()
  {
    return "jethexa_controller_interfaces/SetPose1";
  }

  static const char* value(const ::jethexa_controller_interfaces::SetPose1&) { return value(); }
};


// service_traits::MD5Sum< ::jethexa_controller_interfaces::SetPose1Request> should match
// service_traits::MD5Sum< ::jethexa_controller_interfaces::SetPose1 >
template<>
struct MD5Sum< ::jethexa_controller_interfaces::SetPose1Request>
{
  static const char* value()
  {
    return MD5Sum< ::jethexa_controller_interfaces::SetPose1 >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::SetPose1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::jethexa_controller_interfaces::SetPose1Request> should match
// service_traits::DataType< ::jethexa_controller_interfaces::SetPose1 >
template<>
struct DataType< ::jethexa_controller_interfaces::SetPose1Request>
{
  static const char* value()
  {
    return DataType< ::jethexa_controller_interfaces::SetPose1 >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::SetPose1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jethexa_controller_interfaces::SetPose1Response> should match
// service_traits::MD5Sum< ::jethexa_controller_interfaces::SetPose1 >
template<>
struct MD5Sum< ::jethexa_controller_interfaces::SetPose1Response>
{
  static const char* value()
  {
    return MD5Sum< ::jethexa_controller_interfaces::SetPose1 >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::SetPose1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::jethexa_controller_interfaces::SetPose1Response> should match
// service_traits::DataType< ::jethexa_controller_interfaces::SetPose1 >
template<>
struct DataType< ::jethexa_controller_interfaces::SetPose1Response>
{
  static const char* value()
  {
    return DataType< ::jethexa_controller_interfaces::SetPose1 >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::SetPose1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETPOSE1_H
