// Generated by gencpp from file jethexa_controller_interfaces/SetPose2.msg
// DO NOT EDIT!


#ifndef JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETPOSE2_H
#define JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETPOSE2_H

#include <ros/service_traits.h>


#include <jethexa_controller_interfaces/SetPose2Request.h>
#include <jethexa_controller_interfaces/SetPose2Response.h>


namespace jethexa_controller_interfaces
{

struct SetPose2
{

typedef SetPose2Request Request;
typedef SetPose2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose2
} // namespace jethexa_controller_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jethexa_controller_interfaces::SetPose2 > {
  static const char* value()
  {
    return "595abd8c189b2179c98ec4c165f7d2cd";
  }

  static const char* value(const ::jethexa_controller_interfaces::SetPose2&) { return value(); }
};

template<>
struct DataType< ::jethexa_controller_interfaces::SetPose2 > {
  static const char* value()
  {
    return "jethexa_controller_interfaces/SetPose2";
  }

  static const char* value(const ::jethexa_controller_interfaces::SetPose2&) { return value(); }
};


// service_traits::MD5Sum< ::jethexa_controller_interfaces::SetPose2Request> should match
// service_traits::MD5Sum< ::jethexa_controller_interfaces::SetPose2 >
template<>
struct MD5Sum< ::jethexa_controller_interfaces::SetPose2Request>
{
  static const char* value()
  {
    return MD5Sum< ::jethexa_controller_interfaces::SetPose2 >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::SetPose2Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::jethexa_controller_interfaces::SetPose2Request> should match
// service_traits::DataType< ::jethexa_controller_interfaces::SetPose2 >
template<>
struct DataType< ::jethexa_controller_interfaces::SetPose2Request>
{
  static const char* value()
  {
    return DataType< ::jethexa_controller_interfaces::SetPose2 >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::SetPose2Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jethexa_controller_interfaces::SetPose2Response> should match
// service_traits::MD5Sum< ::jethexa_controller_interfaces::SetPose2 >
template<>
struct MD5Sum< ::jethexa_controller_interfaces::SetPose2Response>
{
  static const char* value()
  {
    return MD5Sum< ::jethexa_controller_interfaces::SetPose2 >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::SetPose2Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::jethexa_controller_interfaces::SetPose2Response> should match
// service_traits::DataType< ::jethexa_controller_interfaces::SetPose2 >
template<>
struct DataType< ::jethexa_controller_interfaces::SetPose2Response>
{
  static const char* value()
  {
    return DataType< ::jethexa_controller_interfaces::SetPose2 >::value();
  }
  static const char* value(const ::jethexa_controller_interfaces::SetPose2Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETHEXA_CONTROLLER_INTERFACES_MESSAGE_SETPOSE2_H
