// Generated by gencpp from file jethexa_controller_interfaces/State.msg
// DO NOT EDIT!


#ifndef JETHEXA_CONTROLLER_INTERFACES_MESSAGE_STATE_H
#define JETHEXA_CONTROLLER_INTERFACES_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jethexa_controller_interfaces
{
template <class ContainerAllocator>
struct State_
{
  typedef State_<ContainerAllocator> Type;

  State_()
    : vin(0.0)  {
    }
  State_(const ContainerAllocator& _alloc)
    : vin(0.0)  {
  (void)_alloc;
    }



   typedef float _vin_type;
  _vin_type vin;





  typedef boost::shared_ptr< ::jethexa_controller_interfaces::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jethexa_controller_interfaces::State_<ContainerAllocator> const> ConstPtr;

}; // struct State_

typedef ::jethexa_controller_interfaces::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::jethexa_controller_interfaces::State > StatePtr;
typedef boost::shared_ptr< ::jethexa_controller_interfaces::State const> StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jethexa_controller_interfaces::State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jethexa_controller_interfaces::State_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jethexa_controller_interfaces::State_<ContainerAllocator1> & lhs, const ::jethexa_controller_interfaces::State_<ContainerAllocator2> & rhs)
{
  return lhs.vin == rhs.vin;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jethexa_controller_interfaces::State_<ContainerAllocator1> & lhs, const ::jethexa_controller_interfaces::State_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jethexa_controller_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jethexa_controller_interfaces::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jethexa_controller_interfaces::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jethexa_controller_interfaces::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jethexa_controller_interfaces::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jethexa_controller_interfaces::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jethexa_controller_interfaces::State_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jethexa_controller_interfaces::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3baec60f92ec7ae546312dfac812d250";
  }

  static const char* value(const ::jethexa_controller_interfaces::State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3baec60f92ec7ae5ULL;
  static const uint64_t static_value2 = 0x46312dfac812d250ULL;
};

template<class ContainerAllocator>
struct DataType< ::jethexa_controller_interfaces::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jethexa_controller_interfaces/State";
  }

  static const char* value(const ::jethexa_controller_interfaces::State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jethexa_controller_interfaces::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vin\n"
;
  }

  static const char* value(const ::jethexa_controller_interfaces::State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jethexa_controller_interfaces::State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vin);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jethexa_controller_interfaces::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jethexa_controller_interfaces::State_<ContainerAllocator>& v)
  {
    s << indent << "vin: ";
    Printer<float>::stream(s, indent + "  ", v.vin);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETHEXA_CONTROLLER_INTERFACES_MESSAGE_STATE_H
