// Generated by gencpp from file jethexa_controller_interfaces/TransformEuler.msg
// DO NOT EDIT!


#ifndef JETHEXA_CONTROLLER_INTERFACES_MESSAGE_TRANSFORMEULER_H
#define JETHEXA_CONTROLLER_INTERFACES_MESSAGE_TRANSFORMEULER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace jethexa_controller_interfaces
{
template <class ContainerAllocator>
struct TransformEuler_
{
  typedef TransformEuler_<ContainerAllocator> Type;

  TransformEuler_()
    : translation()
    , rotation()
    , duration(0.0)  {
    }
  TransformEuler_(const ContainerAllocator& _alloc)
    : translation(_alloc)
    , rotation(_alloc)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _translation_type;
  _translation_type translation;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rotation_type;
  _rotation_type rotation;

   typedef double _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator> const> ConstPtr;

}; // struct TransformEuler_

typedef ::jethexa_controller_interfaces::TransformEuler_<std::allocator<void> > TransformEuler;

typedef boost::shared_ptr< ::jethexa_controller_interfaces::TransformEuler > TransformEulerPtr;
typedef boost::shared_ptr< ::jethexa_controller_interfaces::TransformEuler const> TransformEulerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator1> & lhs, const ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator2> & rhs)
{
  return lhs.translation == rhs.translation &&
    lhs.rotation == rhs.rotation &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator1> & lhs, const ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jethexa_controller_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a328e1cf0b019f32b038faa157f5f4f";
  }

  static const char* value(const ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a328e1cf0b019f3ULL;
  static const uint64_t static_value2 = 0x2b038faa157f5f4fULL;
};

template<class ContainerAllocator>
struct DataType< ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jethexa_controller_interfaces/TransformEuler";
  }

  static const char* value(const ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 translation\n"
"geometry_msgs/Vector3 rotation\n"
"float64 duration\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.translation);
      stream.next(m.rotation);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TransformEuler_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jethexa_controller_interfaces::TransformEuler_<ContainerAllocator>& v)
  {
    s << indent << "translation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.translation);
    s << indent << "rotation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rotation);
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETHEXA_CONTROLLER_INTERFACES_MESSAGE_TRANSFORMEULER_H
